#include "Constants.h"

const std::string Constants::DictionaryFilePath = "words.txt";

const std::vector<std::string> Constants::HangmanHead = { "             .-\"\"\"\"-.","            ////||\\\\\\\\","           ///      \\\\\\" ,"          (    >  <    )" ,"           :     )    ;" ,"            \\   ==   /" ,"             `-.__.-`" };
const std::vector<std::string> Constants::HangmanHands = { "            __.-)__(-,__ ","          ./'  \\_\\_/_/  `\\.","         / >   | //\\ |   < \\" ,"        /  \\   | |/| |   /  \\" ,"       /   |\\  | |/| |  /|   \\" ,"      /   /| \\ | |/| | / |\\   \\" ,"     (   ( |  \\| |/| |/  | )   )" ,"      \\   \\|   Y |/| Y   |/   /" ,"       \\   |  o| |/| |-  |   /" ,"        `\\ |   | `^` |   | /'" ,"          `|  o|=[Ll=|-  |'" ,"           |   /     \\   |" ,"           ~~|`  \\    `|~~" };
const std::vector<std::string> Constants::HangmanLegs = { "             |    |    |" ,"             |    |    |","             |    |    |","             |    |    |","             |    |    |","             |    |    |","             |    |    |","             |    |    |","             |____|____|" ,"             /   / \\   \\" ,"            /   /   \\   \\" ,"           `---'     `---`" };

const std::vector<std::string> Constants::Gibbet1 = { "_________________" };
const std::vector<std::string> Constants::Gibbet2 = { "        |        ","        |        ","        |        ", "        |        ","        |        ", "        |        ", "        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        ","        |        " };//25
const std::vector<std::string> Constants::Gibbet3 = { "____________________" };
const std::vector<std::string> Constants::Gibbet4 = { "                  |","                  |" };